/* ============================================================
   INNER JOIN - Practice Questions
   Database: Bookstore
   Concepts Used:
   - SELECT
   - WHERE
   - DISTINCT
   - ORDER BY
   - Aggregate Functions
   - GROUP BY
   - INNER JOIN
   ============================================================ */


/* ------------------------------------------------------------
   Question 1
   Display each customer's name, the book they purchased,
   and the quantity they bought.
-------------------------------------------------------------*/

select c.customer_name, b.book_name, o.quantity
from customers as c
inner join orders as o
on c.customer_id=o.customer_id
inner join books as b
on o.book_id=b.book_id;

/* ------------------------------------------------------------
   Question 2
   Display all books that cost more than 500.
-------------------------------------------------------------*/

select * from books where  price>500;

/* ------------------------------------------------------------
   Question 3
   Display all customers from Mumbai in alphabetical order.
-------------------------------------------------------------*/

select * from customers where city ='Mumbai'order by customer_name asc;

/* ------------------------------------------------------------
   Question 4
   Display all unique customer cities.
-------------------------------------------------------------*/

select distinct city from customers;

/* ------------------------------------------------------------
   Question 5
   Display customer names who ordered more than
   2 copies of a book.
-------------------------------------------------------------*/

select c.customer_name,o.quantity
from customers as c
inner join orders as o
on c.customer_id = o.customer_id
where o.quantity>2;

/* ------------------------------------------------------------
   Question 6
   Count the total number of orders placed by each customer.

   COUNT(*) counts the number of rows (orders).
-------------------------------------------------------------*/

select c.customer_name, count(*) as No_of_orders
from customers as c 
inner join  orders as o
on c.customer_id= o.customer_id
group by c.customer_name;

/* ------------------------------------------------------------
   Question 7
   Display the total quantity of books purchased
   by each customer.
-------------------------------------------------------------*/

select c.customer_name, sum(o.quantity)
from customers as c
inner join orders as o 
on c.customer_id= o.customer_id 
group by c.customer_name ;

/* ------------------------------------------------------------
   Question 8
   Display the average price of all books.
-------------------------------------------------------------*/

select round(avg(price),2) AS average_book_price
from books;

/* ------------------------------------------------------------
   Question 9
   Display the most expensive and the cheapest book price.
-------------------------------------------------------------*/

select max(price),min(price) from books;

/* ------------------------------------------------------------
   Question 10
   Display the number of orders placed from each city.
-------------------------------------------------------------*/

select c.city, count(*)as total_orders
from customers as c 
inner join orders as o 
on c.customer_id = o.customer_id
group by c.city
order by orders desc 
limit 2;

/* ------------------------------------------------------------
   Question 11
   Display the total revenue generated by each book.
    
      Revenue = Price × Quantity

   GROUP BY is used because we want one row per book.

   SUM(price × quantity) adds the revenue of all
   orders for the same book.
-------------------------------------------------------------*/

select b.book_name , 
sum(b.price*o.quantity) as revenue 
from books as b
inner join orders as o
on b.book_id= o.book_id
group by b.book_name ;
